language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003131

install:
    - export DOTNET_CLI_TELEMETRY_OPTOUT=1

script:
    - dotnet restore 
    - dotnet test ChronoUtils.Tests/project.json
    - dotnet build ChronoUtils/project.json -c Release